import { SignInButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { SignedOutLayout } from "~/components/layout";
import type { NextPageWithLayout } from "./_app";

import { api } from "~/utils/api";
import { ReactElement } from "react";

const Home: NextPageWithLayout = () => {
  // This is our home page where the user will sign in. Once the user has signed
  // in, we'll redirect them to the search page where they can begin looking up
  // their address.

  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Epc builder</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center pt-40">
        <div className=" flex w-1/2 flex-col items-center justify-center bg-slate-100 p-10 drop-shadow-md">
          <h1 className="my-2 text-3xl">Welcome</h1>
          <p className="flexitems-center mb-8 flex justify-center">
            Find out your home&apos;s energy efficiency rating and understand
            the steps you can take to improve it
          </p>
          <p className="mb-3 flex items-center justify-center">
            To get started, sign in below
          </p>
          <SignInButton redirectUrl="/search">
            <button className="rounded bg-blue-500 px-4 py-2 font-bold text-white hover:bg-blue-700">
              Sign in
            </button>
          </SignInButton>
        </div>
      </main>
    </>
  );
};

Home.getLayout = function (page: ReactElement) {
  return <SignedOutLayout>{page}</SignedOutLayout>;
};

export default Home;
